name: nutty
version: 1.0.0
summary: A Network Information Utility
description: A simple application to provide essential information on network related aspects. Nutty provides basic network information, internet usage and speed and monitors devices connected to the network.

icon: data/icons/24/com.github.babluboy.nutty.svg
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
base: core18

slots:
  dbus-nutty:
    interface: dbus
    bus: session
    name: com.github.babluboy.nutty

architectures:
    - build-on: amd64

apps:
  nutty:
    extensions: [gnome-3-34]
    command: usr/bin/com.github.babluboy.nutty
    plugs: [home, x11, wayland, gsettings, unity7, network]

parts:
    nutty:
        source: https://github.com/babluboy/nutty.git
        plugin: meson 
        meson-parameters: [--prefix=/usr]
#        configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
        build-packages:
            - build-essential
            - valac
            - libnotify-dev
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libgranite-dev
            - libsqlite3-dev
            - libxml2-dev
        stage-packages:
            - libpolkit-agent-1-0
            - libpolkit-gobject-1-0
            - gir1.2-polkit-1.0
            - policykit-1
            - gsettings-desktop-schemas
            - libatm1
            - libgranite4
            - gnome-keyring
            - gobject-introspection
            - libgdk-pixbuf2.0-0
            - libgee-0.8-2
            - libgtk-3-0
            - libnotify4
            - libpango-1.0-0
            - libpangocairo-1.0-0
            - net-tools
            - nmap
            - traceroute
            - vnstat
            - nethogs
            - curl
            - wireless-tools
            - iproute2
            - pciutils
#        after: [desktop-gtk3]
layout:
  /usr/share/com.github.babluboy.nutty:
    bind: $SNAP/usr/share/com.github.babluboy.nutty
